echo Moving Personal Configs ;
sleep 3 ;
cp Linuxstuffs/.bashrc ~/.bashrc ;
sudo cp Linuxstuffs/.bashrcroot /root/.bashrc ;
cp Linuxstuffs/wallhaven.jpg ~/Pictures ;
cp -r Linuxstuffs/.config-thinkpad/.Xresources ~/.Xresources ; 
cp -r Linuxstuffs/.config-thinkpad/bspwm ~/.config/ ;
cp -r Linuxstuffs/.config-thinkpad/dunst ~/.config/ ;
cp -r Linuxstuffs/.config-thinkpad/mpd ~/.config/ ;
cp -r Linuxstuffs/.config-thinkpad/polybar ~/.config/ ;
cp -r Linuxstuffs/.config-thinkpad/sxhkd ~/.config/ ; 
#cp -r Linuxstuffs/.config-thinkpad/termite ~/.config/ ;
echo Installing Useful Shit ;
sleep 3 ;
echo Tools ;
sudo pacman -Syyyu base-devel multilib-devel cmake make svn clang lzip patchelf inetutils python2-distlib xorg xorg-server android-tools android-udev
echo bspwm ;
sudo pacman -S --noconfirm bspwm dunst mpd polybar sxhkd pulseaudio pavucontrol ;
cd ;
echo Paru ;
sleep 3 ;
git clone https://aur.archlinux.org/paru.git ;
cd paru/ ;
makepkg -si ;
cd ;
paru -S gradle maven protontricks matcha-gtk-theme qogir-icon-theme ;
git config --global user.email ktnxbaii@gmail.com ; git config --global user.name ktnxd ;
cowsay -f tux rebooting in 60..59..58.. ;
sleep 3 ;
clear ;
cowsay -f tux joke kbai ;
sleep 2 ;
sudo reboot ;
