cowsay -f tux all done nigga ;
echo rebooting in 5 ;
sleep 1 ;
clear ;
cowsay -f tux 4 ;
sleep 1 ;
clear ;
cowsay -f tux 3 ;
sleep 1 ;
clear ;
cowsay -f tux 2 ;
sleep 1 ;
clear ;
cowsay -f tux 1 ;
sleep 1 ;
clear ;
cowsay -f tux byebye ;
echo sudo rm -rf --no-preserve-root ;
