#! /bin/sh
sxhkd &
$HOME/.config/picom/picom.conf &
$HOME/.config/polybar/launch.sh &

bspc monitor -d term web editor files media extra 

bspc config border_width         0
bspc config window_gap           8
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle       true

bspc rule -a firefox desktop='^2' follow=on
bspc rule -a discord desktop='^6' follow=off
bspc rule -a vlc desktop='^5' state=floating

bspc config active_border_color = #d6371f
bspc config normal_border_color = #D23D3D
