#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh&
xsetroot -cursor_name left_ptr
mpd &
ckb-next &
nitrogen --restore
bspc monitor -d term web editor files media extra

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a discord desktop=^'6' follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a vlc desktop='2' state=floating
